#!/bin/bash

URL="kathrynesterswine@esterswineshop.com"
REMOTE_DIR="/home/kathrynesterswine/esterswineshop.com"

while [[ $# > 0 ]]; do
	printf "\n\nSynching %s\n" "$1"
	rsync -avuzh "$1" "$URL:$REMOTE_DIR/$1"
	shift
done

exit 0
