<?php
function get_theme_custom_fields_definitions() {
	$fields = [
		'home_slides' => array(
			array(
				'key' => 'field_5886600649550',
				'label' => 'slider',
				'name' => 'slider',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5886601749551',
						'label' => 'hero image',
						'name' => 'hero_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'return_format' => 'url',
						'min_width' => 0,
						'min_height' => 0,
						'min_size' => 0,
						'max_width' => 0,
						'max_height' => 0,
						'max_size' => 0,
						'mime_types' => '',
					),
					array(
						'key' => 'field_5886603149552',
						'label' => 'Hero Title',
						'name' => 'hero_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5886605f49553',
						'label' => 'Sub Copy',
						'name' => 'sub_copy',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => 'br',
					),
					array(
						'key' => 'field_5886607849554',
						'label' => 'Call-to-action',
						'name' => 'call-to-action',
						'type' => 'page_link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
						),
						'allow_null' => 1,
						'multiple' => 0,
						'taxonomy' => array(
						),
						'allow_archives' => 1,
					),
				),
			),
		),
		'events' => array(
			array(
				'key' => 'field_55aeea20ba8fc',
				'label' => 'Display Date',
				'name' => 'date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'first_day' => 0,
				'return_format' => 'd/m/Y',
				'display_format' => 'Y-m-d',
				'save_format' => 'M<span>dd</span>D',
			),
			array(
				'key' => 'field_564253dfc39d4',
				'label' => 'Date',
				'name' => 'real_date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'first_day' => 0,
				'return_format' => 'd/m/Y',
				'display_format' => 'Y-m-d',
				'save_format' => 'yy-mm-dd',
			),
			array(
				'key' => 'field_561ef4cd922d8',
				'label' => 'Time',
				'name' => 'time',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array(
				'key' => 'field_55aeea39ba8fd',
				'label' => 'Image One',
				'name' => 'image_one',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'preview_size' => 'full',
				'library' => 'all',
				'return_format' => 'url',
				'min_width' => 0,
				'min_height' => 0,
				'min_size' => 0,
				'max_width' => 0,
				'max_height' => 0,
				'max_size' => 0,
				'mime_types' => '',
			),
			array(
				'key' => 'field_55aeea6fba8ff',
				'label' => 'Brief Description',
				'name' => 'brief_description',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_55aeea85ba900',
				'label' => 'Full Description',
				'name' => 'full_description',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 1,
				'tabs' => 'all',
				'delay' => 0,
			),
		),
		'press' => array(
			array(
				'key' => 'field_55d757b7ab68e',
				'label' => 'Press Image',
				'name' => 'press_image',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'preview_size' => 'medium',
				'library' => 'all',
				'return_format' => 'array',
				'min_width' => 0,
				'min_height' => 0,
				'min_size' => 0,
				'max_width' => 0,
				'max_height' => 0,
				'max_size' => 0,
				'mime_types' => '',
			),
			array(
				'key' => 'field_55d757c4ab68f',
				'label' => 'Source Name',
				'name' => 'source_name',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array(
				'key' => 'field_55d757cbab690',
				'label' => 'Article Link',
				'name' => 'article_link',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
		),
		'menu' => array(
			array(
				'key' => 'field_59d401c3fb123',
				'label' => 'Menu Announcement Bar',
				'name' => 'menu_note',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_59c5729aa77bb',
				'label' => 'Dinner',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_59d3f631a9135',
				'label' => 'Menu Note',
				'name' => 'note_dinner',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_59d51970c35a4',
				'label' => 'Menu Sections - Left Side',
				'name' => 'menu_section_dinner_left',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'59d41e0287195' => array(
						'key' => '59d41e0287195',
						'name' => 'menu_section',
						'label' => 'Menu Section - Left Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d51970c35a5',
								'label' => 'Menu Section Title',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d51970c35a6',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d51970c35a7',
								'label' => 'Menu Items',
								'name' => 'menu_items',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Item',
								'sub_fields' => array(
									array(
										'key' => 'field_59d51970c35a8',
										'label' => 'Menu Item',
										'name' => 'menu_item',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'59d41fb0a7346' => array(
						'key' => '59d41fb0a7346',
						'name' => 'menu_subsections',
						'label' => 'Menu Section with Subsections - Left Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d51970c35aa',
								'label' => 'Menu Section Title',
								'name' => 'title_subsections',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d51970c35ab',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d51970c35ac',
								'label' => 'Subsections',
								'name' => 'subsections',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Subsection',
								'sub_fields' => array(
									array(
										'key' => 'field_59d51970c35ad',
										'label' => 'Subsection Title',
										'name' => 'subsection_title',
										'type' => 'text',
										'instructions' => 'Leave this blank if you want to add menu items without a subsection title.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d51970c35ae',
										'label' => 'Subsection Note',
										'name' => 'subsection_note',
										'type' => 'text',
										'instructions' => 'Optional',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d51970c35af',
										'label' => 'Menu Items',
										'name' => 'menu_items',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'block',
										'button_label' => 'Add Menu Item',
										'sub_fields' => array(
											array(
												'key' => 'field_59d51970c35b0',
												'label' => 'Menu Item',
												'name' => 'menu_item',
												'type' => 'wysiwyg',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'basic',
												'media_upload' => 0,
												'delay' => 0,
											),
										),
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Menu Section (Left Side)',
				'min' => '',
				'max' => '',
			),
			array(
				'key' => 'field_59d5197dc35b2',
				'label' => 'Menu Sections - Right Side',
				'name' => 'menu_section_dinner_right',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'59d41e0287195' => array(
						'key' => '59d41e0287195',
						'name' => 'menu_section',
						'label' => 'Menu Section - Right Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d5197dc35b3',
								'label' => 'Menu Section Title',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d5197dc35b4',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d5197dc35b5',
								'label' => 'Menu Items',
								'name' => 'menu_items',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Item',
								'sub_fields' => array(
									array(
										'key' => 'field_59d5197dc35b6',
										'label' => 'Menu Item',
										'name' => 'menu_item',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'59d41fb0a7346' => array(
						'key' => '59d41fb0a7346',
						'name' => 'menu_subsections',
						'label' => 'Menu Section with Subsections - Right Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d5197dc35b8',
								'label' => 'Menu Section Title',
								'name' => 'title_subsections',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d5197dc35b9',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d5197dc35ba',
								'label' => 'Subsections',
								'name' => 'subsections',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Subsection',
								'sub_fields' => array(
									array(
										'key' => 'field_59d5197dc35bb',
										'label' => 'Subsection Title',
										'name' => 'subsection_title',
										'type' => 'text',
										'instructions' => 'Leave this blank if you want to add menu items without a subsection title.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d5197dc35bc',
										'label' => 'Subsection Note',
										'name' => 'subsection_note',
										'type' => 'text',
										'instructions' => 'Optional',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d5197dc35bd',
										'label' => 'Menu Items',
										'name' => 'menu_items',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'block',
										'button_label' => 'Add Menu Item',
										'sub_fields' => array(
											array(
												'key' => 'field_59d5197dc35be',
												'label' => 'Menu Item',
												'name' => 'menu_item',
												'type' => 'wysiwyg',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'basic',
												'media_upload' => 0,
												'delay' => 0,
											),
										),
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Menu Section (Right Side)',
				'min' => '',
				'max' => '',
			),
			array(
				'key' => 'field_59c5728ea77ba',
				'label' => 'Lunch',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_59d3f688244cd',
				'label' => 'Menu Note',
				'name' => 'note_lunch',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_59d51363d75a1',
				'label' => 'Menu Sections - Left Side',
				'name' => 'menu_section_lunch_left',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'59d41e0287195' => array(
						'key' => '59d41e0287195',
						'name' => 'menu_section',
						'label' => 'Menu Section - Left Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d51363d75a2',
								'label' => 'Menu Section Title',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d51363d75a3',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d51363d75a4',
								'label' => 'Menu Items',
								'name' => 'menu_items',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Item',
								'sub_fields' => array(
									array(
										'key' => 'field_59d51363d75a5',
										'label' => 'Menu Item',
										'name' => 'menu_item',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'59d41fb0a7346' => array(
						'key' => '59d41fb0a7346',
						'name' => 'menu_subsections',
						'label' => 'Menu Section with Subsections - Left Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d51363d75a7',
								'label' => 'Menu Section Title',
								'name' => 'title_subsections',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d51363d75a8',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d51363d75a9',
								'label' => 'Subsections',
								'name' => 'subsections',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Subsection',
								'sub_fields' => array(
									array(
										'key' => 'field_59d51363d75aa',
										'label' => 'Subsection Title',
										'name' => 'subsection_title',
										'type' => 'text',
										'instructions' => 'Leave this blank if you want to add menu items without a subsection title.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d51363d75ab',
										'label' => 'Subsection Note',
										'name' => 'subsection_note',
										'type' => 'text',
										'instructions' => 'Optional',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d51363d75ac',
										'label' => 'Menu Items',
										'name' => 'menu_items',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'block',
										'button_label' => 'Add Menu Item',
										'sub_fields' => array(
											array(
												'key' => 'field_59d51363d75ad',
												'label' => 'Menu Item',
												'name' => 'menu_item',
												'type' => 'wysiwyg',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'basic',
												'media_upload' => 0,
												'delay' => 0,
											),
										),
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Menu Section (Left Side)',
				'min' => '',
				'max' => '',
			),
			array(
				'key' => 'field_59d4fc9d79feb',
				'label' => 'Menu Sections - Right Side',
				'name' => 'menu_section_lunch_right',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'59d41e0287195' => array(
						'key' => '59d41e0287195',
						'name' => 'menu_section',
						'label' => 'Menu Section - Right Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d4fc9e79fec',
								'label' => 'Menu Section Title',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d4fccd79ff5',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d4fc9e79fed',
								'label' => 'Menu Items',
								'name' => 'menu_items',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Item',
								'sub_fields' => array(
									array(
										'key' => 'field_59d4fc9e79fee',
										'label' => 'Menu Item',
										'name' => 'menu_item',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'59d41fb0a7346' => array(
						'key' => '59d41fb0a7346',
						'name' => 'menu_subsections',
						'label' => 'Menu Section with Subsections - Right Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d4fc9e79fef',
								'label' => 'Menu Section Title',
								'name' => 'title_subsections',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d4fcef79ff6',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d4fc9e79ff0',
								'label' => 'Subsections',
								'name' => 'subsections',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Subsection',
								'sub_fields' => array(
									array(
										'key' => 'field_59d4fc9e79ff1',
										'label' => 'Subsection Title',
										'name' => 'subsection_title',
										'type' => 'text',
										'instructions' => 'Leave this blank if you want to add menu items without a subsection title.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d4fc9e79ff2',
										'label' => 'Subsection Note',
										'name' => 'subsection_note',
										'type' => 'text',
										'instructions' => 'Optional',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d4fc9e79ff3',
										'label' => 'Menu Items',
										'name' => 'menu_items',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'block',
										'button_label' => 'Add Menu Item',
										'sub_fields' => array(
											array(
												'key' => 'field_59d4fc9e79ff4',
												'label' => 'Menu Item',
												'name' => 'menu_item',
												'type' => 'wysiwyg',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'basic',
												'media_upload' => 0,
												'delay' => 0,
											),
										),
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Menu Section (Right Side)',
				'min' => '',
				'max' => '',
			),
			array(
				'key' => 'field_59c57208a77b9',
				'label' => 'Brunch',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_59c93a6e4c18a',
				'label' => 'Menu Note',
				'name' => 'note_brunch',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_59d52cba1f498',
				'label' => 'Menu Sections - Left Side',
				'name' => 'menu_section_brunch_left',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'59d41e0287195' => array(
						'key' => '59d41e0287195',
						'name' => 'menu_section',
						'label' => 'Menu Section - Left Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d52cba1f499',
								'label' => 'Menu Section Title',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52cba1f49a',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52cba1f49b',
								'label' => 'Menu Items',
								'name' => 'menu_items',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Item',
								'sub_fields' => array(
									array(
										'key' => 'field_59d52cba1f49c',
										'label' => 'Menu Item',
										'name' => 'menu_item',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'59d41fb0a7346' => array(
						'key' => '59d41fb0a7346',
						'name' => 'menu_subsections',
						'label' => 'Menu Section with Subsections - Left Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d52cba1f49e',
								'label' => 'Menu Section Title',
								'name' => 'title_subsections',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52cba1f49f',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52cba1f4a0',
								'label' => 'Subsections',
								'name' => 'subsections',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Subsection',
								'sub_fields' => array(
									array(
										'key' => 'field_59d52cba1f4a1',
										'label' => 'Subsection Title',
										'name' => 'subsection_title',
										'type' => 'text',
										'instructions' => 'Leave this blank if you want to add menu items without a subsection title.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d52cba1f4a2',
										'label' => 'Subsection Note',
										'name' => 'subsection_note',
										'type' => 'text',
										'instructions' => 'Optional',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d52cba1f4a3',
										'label' => 'Menu Items',
										'name' => 'menu_items',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'block',
										'button_label' => 'Add Menu Item',
										'sub_fields' => array(
											array(
												'key' => 'field_59d52cba1f4a4',
												'label' => 'Menu Item',
												'name' => 'menu_item',
												'type' => 'wysiwyg',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'basic',
												'media_upload' => 0,
												'delay' => 0,
											),
										),
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Menu Section (Left Side)',
				'min' => '',
				'max' => '',
			),
			array(
				'key' => 'field_59d52cc31f4a6',
				'label' => 'Menu Sections - Right Side',
				'name' => 'menu_section_brunch_right',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'59d41e0287195' => array(
						'key' => '59d41e0287195',
						'name' => 'menu_section',
						'label' => 'Menu Section - Right Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d52cc31f4a7',
								'label' => 'Menu Section Title',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52cc31f4a8',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52cc31f4a9',
								'label' => 'Menu Items',
								'name' => 'menu_items',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Item',
								'sub_fields' => array(
									array(
										'key' => 'field_59d52cc31f4aa',
										'label' => 'Menu Item',
										'name' => 'menu_item',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'59d41fb0a7346' => array(
						'key' => '59d41fb0a7346',
						'name' => 'menu_subsections',
						'label' => 'Menu Section with Subsections - Right Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d52cc31f4ac',
								'label' => 'Menu Section Title',
								'name' => 'title_subsections',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52cc31f4ad',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52cc31f4ae',
								'label' => 'Subsections',
								'name' => 'subsections',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Subsection',
								'sub_fields' => array(
									array(
										'key' => 'field_59d52cc31f4af',
										'label' => 'Subsection Title',
										'name' => 'subsection_title',
										'type' => 'text',
										'instructions' => 'Leave this blank if you want to add menu items without a subsection title.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d52cc31f4b0',
										'label' => 'Subsection Note',
										'name' => 'subsection_note',
										'type' => 'text',
										'instructions' => 'Optional',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d52cc31f4b1',
										'label' => 'Menu Items',
										'name' => 'menu_items',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'block',
										'button_label' => 'Add Menu Item',
										'sub_fields' => array(
											array(
												'key' => 'field_59d52cc31f4b2',
												'label' => 'Menu Item',
												'name' => 'menu_item',
												'type' => 'wysiwyg',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '-1',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'basic',
												'media_upload' => 0,
												'delay' => 0,
											),
										),
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Menu Section (Right Side)',
				'min' => '',
				'max' => '',
			),
			array(
				'key' => 'field_59c572b0a77bc',
				'label' => 'Drinks',
				'name' => '',
				'type' => 'tab',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'placement' => 'top',
				'endpoint' => 0,
			),
			array(
				'key' => 'field_59d3f746da6c0',
				'label' => 'Menu Note',
				'name' => 'note_drinks',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_59d3f75dda6c1',
				'label' => 'Wine List Text',
				'name' => 'wine_list_text',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'maxlength' => '',
			),
			array(
				'key' => 'field_59d3f77eda6c2',
				'label' => 'Wine List PDF',
				'name' => 'wine_list_pdf',
				'type' => 'file',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'url',
				'library' => 'all',
				'min_size' => '',
				'max_size' => '',
				'mime_types' => '',
			),
			array(
				'key' => 'field_59d52a2b803ff',
				'label' => 'Menu Sections - Left Side',
				'name' => 'menu_section_drinks_left',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'59d41e0287195' => array(
						'key' => '59d41e0287195',
						'name' => 'menu_section',
						'label' => 'Menu Section - Left Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d52a2c80400',
								'label' => 'Menu Section Title',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52a2c80401',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52a2c80402',
								'label' => 'Menu Items',
								'name' => 'menu_items',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Item',
								'sub_fields' => array(
									array(
										'key' => 'field_59d52a2c80403',
										'label' => 'Menu Item',
										'name' => 'menu_item',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'59d41fb0a7346' => array(
						'key' => '59d41fb0a7346',
						'name' => 'menu_subsections',
						'label' => 'Menu Section with Subsections - Left Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d52a2c80405',
								'label' => 'Menu Section Title',
								'name' => 'title_subsections',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52a2c80406',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52a2c80407',
								'label' => 'Subsections',
								'name' => 'subsections',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Subsection',
								'sub_fields' => array(
									array(
										'key' => 'field_59d52a2c80408',
										'label' => 'Subsection Title',
										'name' => 'subsection_title',
										'type' => 'text',
										'instructions' => 'Leave this blank if you want to add menu items without a subsection title.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d52a2c80409',
										'label' => 'Subsection Note',
										'name' => 'subsection_note',
										'type' => 'text',
										'instructions' => 'Optional',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d52a2c8040a',
										'label' => 'Menu Items',
										'name' => 'menu_items',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'block',
										'button_label' => 'Add Menu Item',
										'sub_fields' => array(
											array(
												'key' => 'field_59d52a2c8040b',
												'label' => 'Menu Item',
												'name' => 'menu_item',
												'type' => 'wysiwyg',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'basic',
												'media_upload' => 0,
												'delay' => 0,
											),
										),
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Menu Section (Left Side)',
				'min' => '',
				'max' => '',
			),
			array(
				'key' => 'field_59d52a1b803f1',
				'label' => 'Menu Sections - Right Side',
				'name' => 'menu_section_drinks_right',
				'type' => 'flexible_content',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'layouts' => array(
					'59d41e0287195' => array(
						'key' => '59d41e0287195',
						'name' => 'menu_section',
						'label' => 'Menu Section - Right Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d52a1b803f2',
								'label' => 'Menu Section Title',
								'name' => 'title',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52a1b803f3',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52a1b803f4',
								'label' => 'Menu Items',
								'name' => 'menu_items',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Item',
								'sub_fields' => array(
									array(
										'key' => 'field_59d52a1b803f5',
										'label' => 'Menu Item',
										'name' => 'menu_item',
										'type' => 'wysiwyg',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'tabs' => 'all',
										'toolbar' => 'basic',
										'media_upload' => 0,
										'delay' => 0,
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
					'59d41fb0a7346' => array(
						'key' => '59d41fb0a7346',
						'name' => 'menu_subsections',
						'label' => 'Menu Section with Subsections - Right Side',
						'display' => 'block',
						'sub_fields' => array(
							array(
								'key' => 'field_59d52a1b803f7',
								'label' => 'Menu Section Title',
								'name' => 'title_subsections',
								'type' => 'text',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52a1b803f8',
								'label' => 'Menu Section Note',
								'name' => 'menu_section_note',
								'type' => 'text',
								'instructions' => 'Optional',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'default_value' => '',
								'placeholder' => '',
								'prepend' => '',
								'append' => '',
								'maxlength' => '',
							),
							array(
								'key' => 'field_59d52a1b803f9',
								'label' => 'Subsections',
								'name' => 'subsections',
								'type' => 'repeater',
								'instructions' => '',
								'required' => 0,
								'conditional_logic' => 0,
								'wrapper' => array(
									'width' => '',
									'class' => '',
									'id' => '',
								),
								'collapsed' => '',
								'min' => 0,
								'max' => 0,
								'layout' => 'block',
								'button_label' => 'Add Menu Subsection',
								'sub_fields' => array(
									array(
										'key' => 'field_59d52a1b803fa',
										'label' => 'Subsection Title',
										'name' => 'subsection_title',
										'type' => 'text',
										'instructions' => 'Leave this blank if you want to add menu items without a subsection title.',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d52a1b803fb',
										'label' => 'Subsection Note',
										'name' => 'subsection_note',
										'type' => 'text',
										'instructions' => 'Optional',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'default_value' => '',
										'placeholder' => '',
										'prepend' => '',
										'append' => '',
										'maxlength' => '',
									),
									array(
										'key' => 'field_59d52a1b803fc',
										'label' => 'Menu Items',
										'name' => 'menu_items',
										'type' => 'repeater',
										'instructions' => '',
										'required' => 0,
										'conditional_logic' => 0,
										'wrapper' => array(
											'width' => '',
											'class' => '',
											'id' => '',
										),
										'collapsed' => '',
										'min' => 0,
										'max' => 0,
										'layout' => 'block',
										'button_label' => 'Add Menu Item',
										'sub_fields' => array(
											array(
												'key' => 'field_59d52a1b803fd',
												'label' => 'Menu Item',
												'name' => 'menu_item',
												'type' => 'wysiwyg',
												'instructions' => '',
												'required' => 0,
												'conditional_logic' => 0,
												'wrapper' => array(
													'width' => '',
													'class' => '',
													'id' => '',
												),
												'default_value' => '',
												'tabs' => 'all',
												'toolbar' => 'basic',
												'media_upload' => 0,
												'delay' => 0,
											),
										),
									),
								),
							),
						),
						'min' => '',
						'max' => '',
					),
				),
				'button_label' => 'Add Menu Section (Right Side)',
				'min' => '',
				'max' => '',
			),
		),
	];
	if (function_exists('acf_add_local_field_group')) {
		acf_add_local_field_group(array(
			'key' => 'group_59ca6fee1edb0',
			'title' => 'Event',
			'fields' => $fields['events'],
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'calendar-event',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => array(
				0 => 'the_content',
			),
			'active' => true,
			'description' => '',
		));

		acf_add_local_field_group(array(
			'key' => 'group_59ca6fee55325',
			'title' => 'Homepage Slider',
			'fields' => $fields['home_slides'],
			'location' => array(
				array(
					array(
						'param' => 'page',
						'operator' => '==',
						'value' => '664',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => array(
			),
			'active' => true,
			'description' => '',
		));

		acf_add_local_field_group(array(
			'key' => 'group_59ca6fef13e10',
			'title' => 'Press',
			'fields' => $fields['press'],
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'press',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'acf_after_title',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => array(
				0 => 'the_content',
			),
			'active' => true,
			'description' => '',
		));

		/*
		acf_add_local_field_group(array(
			'key' => 'group_59c571f95598f',
			'title' => 'Menu',
			'fields' => $fields['menu'],
			'location' => array(
				array(
					array(
						'param' => 'page',
						'operator' => '==',
						'value' => '433',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'acf_after_title',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => array(
				0 => 'the_content',
				1 => 'featured_image',
			),
			'active' => true,
			'description' => '',
		));
		 */

		return $fields;
	}
	return FALSE;
}
