<?php
function get_theme_custom_fields_definitions() {
	$fields = [
		'home_slides' => array(
			array(
				'key' => 'field_5886600649550',
				'label' => 'slider',
				'name' => 'slider',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'row_min' => '',
				'row_limit' => '',
				'layout' => 'table',
				'button_label' => 'Add Row',
				'min' => 0,
				'max' => 0,
				'collapsed' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_5886601749551',
						'label' => 'hero image',
						'name' => 'hero_image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'return_format' => 'url',
						'min_width' => 0,
						'min_height' => 0,
						'min_size' => 0,
						'max_width' => 0,
						'max_height' => 0,
						'max_size' => 0,
						'mime_types' => '',
					),
					array(
						'key' => 'field_5886603149552',
						'label' => 'Hero Title',
						'name' => 'hero_title',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'formatting' => 'html',
						'maxlength' => '',
					),
					array(
						'key' => 'field_5886605f49553',
						'label' => 'Sub Copy',
						'name' => 'sub_copy',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'maxlength' => '',
						'rows' => '',
						'new_lines' => 'br',
					),
					array(
						'key' => 'field_5886607849554',
						'label' => 'Call-to-action',
						'name' => 'call-to-action',
						'type' => 'page_link',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'post_type' => array(
						),
						'allow_null' => 1,
						'multiple' => 0,
						'taxonomy' => array(
						),
						'allow_archives' => 1,
					),
				),
			),
		),
		'events' => array(
			array(
				'key' => 'field_55aeea20ba8fc',
				'label' => 'Display Date',
				'name' => 'date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'first_day' => 0,
				'return_format' => 'd/m/Y',
				'display_format' => 'Y-m-d',
				'save_format' => 'M<span>dd</span>D',
			),
			array(
				'key' => 'field_564253dfc39d4',
				'label' => 'Date',
				'name' => 'real_date',
				'type' => 'date_picker',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'first_day' => 0,
				'return_format' => 'd/m/Y',
				'display_format' => 'Y-m-d',
				'save_format' => 'yy-mm-dd',
			),
			array(
				'key' => 'field_561ef4cd922d8',
				'label' => 'Time',
				'name' => 'time',
				'type' => 'text',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array(
				'key' => 'field_55aeea39ba8fd',
				'label' => 'Image One',
				'name' => 'image_one',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'preview_size' => 'full',
				'library' => 'all',
				'return_format' => 'url',
				'min_width' => 0,
				'min_height' => 0,
				'min_size' => 0,
				'max_width' => 0,
				'max_height' => 0,
				'max_size' => 0,
				'mime_types' => '',
			),
			array(
				'key' => 'field_55aeea6fba8ff',
				'label' => 'Brief Description',
				'name' => 'brief_description',
				'type' => 'textarea',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => 3,
				'new_lines' => 'br',
			),
			array(
				'key' => 'field_55aeea85ba900',
				'label' => 'Full Description',
				'name' => 'full_description',
				'type' => 'wysiwyg',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'default_value' => '',
				'toolbar' => 'full',
				'media_upload' => 1,
				'tabs' => 'all',
				'delay' => 0,
			),
		),
	];
	if (function_exists('acf_add_local_field_group')) {
		acf_add_local_field_group(array(
			'key' => 'group_59ca6fee1edb0',
			'title' => 'Event',
			'fields' => $fields['events'],
			'location' => array(
				array(
					array(
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'calendar-event',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => array(
				0 => 'the_content',
			),
			'active' => true,
			'description' => '',
		));

		acf_add_local_field_group(array(
			'key' => 'group_59ca6fee55325',
			'title' => 'Homepage Slider',
			'fields' => $fields['home_slides'],
			'location' => array(
				array(
					array(
						'param' => 'page',
						'operator' => '==',
						'value' => '664',
					),
				),
			),
			'menu_order' => 0,
			'position' => 'normal',
			'style' => 'default',
			'label_placement' => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen' => array(
			),
			'active' => true,
			'description' => '',
		));

		return $fields;
	}
	return FALSE;
}
