<?php
if (function_exists("register_field_group")) register_field_group(array (
	'id' => 'acf_private-events',
	'title' => 'Private Events',
	'fields' => array (
		array(
			'key' => 'field_5b7f0dc6a1d9c',
			'label' => 'Gather Here Location ID',
			'name' => 'gather_location_id',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array (
			'key' => 'field_588a448046f6d',
			'label' => 'Events Slider',
			'name' => 'events_slider',
			'type' => 'repeater',
			'sub_fields' => array (
				array (
					'key' => 'field_588a44ac46f6e',
					'label' => 'Slider Image',
					'name' => 'slider_image',
					'type' => 'image',
					'column_width' => '',
					'save_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
				array (
					'key' => 'field_588a44c546f6f',
					'label' => 'Slider Title',
					'name' => 'slider_title',
					'type' => 'text',
					'column_width' => '',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_588a44e146f70',
					'label' => 'Slider Copy',
					'name' => 'slider_copy',
					'type' => 'wysiwyg',
					'column_width' => '',
					'default_value' => '',
					'toolbar' => 'full',
					'media_upload' => 'no',
				),
			),
			'row_min' => '',
			'row_limit' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'template-private-events.php',
				'order_no' => 0,
				'group_no' => 0,
			),
		),
	),
	'options' => array (
		'position' => 'normal',
		'layout' => 'default',
		'hide_on_screen' => array (
		),
	),
	'menu_order' => 0,
));
